name: 'Muurschilderingendatabase ETL'

env:
  BASE_URI: 'https://muurschilderingendatabase.nl/'
  PROJECT_NAME: 'Muurschilderingendatabase ETL'
  TARGET_FILEPATH: 'data/api-export.ttl'
  GRAPH_ID: 'muurschilderingen-latest-graph'
  ARTIFACT_PATH: 'data/artifact-data.ttl'

on:
  workflow_dispatch:

jobs:
  get-latest-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Get latest data from Muurschilderingendatabase
      run: |
        python scripts/export_from_omeka_s.py
      env:
        BASE_URI: ${{ env.BASE_URI }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        TARGET_FILEPATH: ${{ env.ARTIFACT_PATH }}
        GRAPH_ID: ${{ env.GRAPH_ID }}   
    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        name: data-artifact
        path: ${{ env.ARTIFACT_PATH }}
        overwrite: true

  transform-enrich:
    runs-on: ubuntu-latest
    needs: get-latest-data
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download data artifact
      uses: actions/download-artifact@v5
      with:
        name: data-artifact
        path: data
    - name: Transform and enrich data
      run: |
        python scripts/transform_datamodel.py
      env:
        BASE_URI: ${{ env.BASE_URI }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        TARGET_FILEPATH: ${{ env.ARTIFACT_PATH }}
        GRAPH_ID: ${{ env.GRAPH_ID }}   
    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        name: data-artifact
        path: ${{ env.ARTIFACT_PATH }}
        overwrite: true

  push-to-github:
    runs-on: ubuntu-latest
    needs: [get-latest-data, transform-enrich]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Download data artifact
      uses: actions/download-artifact@v5
      with:
        name: data-artifact
        path: data
    - name: Replace ttl file with ubuntu-latest
      run: |
        mv ${{ env.ARTIFACT_PATH }} ${{ env.TARGET_FILEPATH }}    
    - name: Check for changes and commit latest data to repository.
      run: |
        if [[ -n $(git status -s) ]]; then
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add ${{ github.workspace }}/${{ env.TARGET_FILEPATH }}
          git commit -m "Muurschilderingendatabase export/transform update."
          git push
        fi

  push-to-triply:
    runs-on: ubuntu-latest
    needs: [get-latest-data, transform-enrich]
    steps:
    - name: Download data artifact
      uses: actions/download-artifact@v5
      with:
          name: data-artifact
          path: data
    - name: Install dependencies
      run: |
        wget 'https://static.triply.cc/cli/triplydb-linux'
        chmod +x triplydb-linux
    - name: Push changes to TriplyDB API via CLI
      run: |
        ./triplydb-linux import-from-file --dataset "Muurschilderingen" --token "${{ secrets.LDV_API_TOKEN }}" --account "rce" --url "https://api.linkeddata.cultureelerfgoed.nl" --default-graph-name 'https://linkeddata.cultureelerfgoed.nl/rce/Muurschilderingen/graphs/${{ env.GRAPH_ID }}' --mode "overwrite" ${{ env.ARTIFACT_PATH }}
