name: 'Muurschilderingendatabase ETL'

env:
  BASE_URI: 'https://muurschilderingendatabase.nl/'  
  PROJECT_NAME: 'Muurschilderingendatabase ETL'
  TARGET_FILEPATH: 'data/api-export.ttl'

on:
  workflow_dispatch:
  
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run harvester script
      run: |
        python scripts/export_from_omeka_s.py
      env:
        BASE_URI: ${{ env.BASE_URI }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        TARGET_FILEPATH: ${{ env.TARGET_FILEPATH }}

    - name: Transform and make available in repository.
      run: |
        python scripts/transform_datamodel.py
      env:
        BASE_URI: ${{ env.BASE_URI }}
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        TARGET_FILEPATH: ${{ env.TARGET_FILEPATH }}

    - name: Check for changes
      run: |
        if [[ -n $(git status -s) ]]; then
          git config user.name github-actions[bot]
          git config user.email [github-actions-id]+github-actions[bot]@users.noreply.github.com
          git add ${{ github.workspace }}/${{ env.TARGET_FILEPATH }}
          git commit -m "Muurschilderingendatabase export/transform update."
          git push        
        fi
